# Generated by Django 3.1.1 on 2020-11-03 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('form', models.TextField()),
                ('mate', models.TextField()),
                ('method', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('size_d', models.IntegerField(blank=True, null=True)),
                ('size_w', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
